# infrastructure/docker/nginx/nginx.conf
events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout 65;

    gzip on;
    gzip_types text/plain application/json application/javascript text/css;

    upstream backend {
        server backend:3001;
    }

    upstream frontend {
        server frontend:3000;
    }

    upstream socket {
        server socket-server:3002;
    }

    include /etc/nginx/conf.d/*.conf;
}
